- name: Windows SSH setup
  hosts: windows
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
  - import_role: 
      name: win_service_config
      vars_from: ./ssh_var.yml