---
# tasks file for win_service_config

- name: Install SSH with Choclatey
  win_chocolatey:
    name: "{{ package_name }}"
    state: reinstalled
    params: "{{ parameters }}"


- name: Autostart and start SSH service
  win_service:
    name: "{{ service_name }}"
    start_mode: auto
    state: started

- name: Allow inbound TCP/22 through firewall
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes