---

- name: Repository configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
  - import_role: 
      name: repo-config

- name: deploy and configure haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
    - import_role:
        name: haproxy

- name: deploy and configure tomcat and add web pages
  hosts: apps
  gather_facts: false
  become: true

  tasks:
    - import_role:
        name: tomcat

- name: deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true
  hosts: appdbs
  tasks:
  - include_tasks: postgres.yml
