- name: install tomcat
  package:
    name: tomcat
    state: latest

- name: enable tomcat at boot
  service:
    name: tomcat
    enabled: yes

- name: start tomcat
  service:
    name: tomcat
    state: started

- name: create ROOT tomcat directory
  file:
    path: /usr/share/tomcat/webapps/ROOT
    state: directory
    recurse: yes

- name: copy static index.html to tomcat's ROOT directory
  template:
    src: ../templates/index.html.j2
    dest: /usr/share/tomcat/webapps/ROOT/index.html
    mode: 0644
  notify:   
  - restart_tomcat